digital_channels_number = 16
analog_channels_number = 16
dds_channels_number = 12
sampler_channels_number = 8
package_manager = "conda" # it can be either conda or clang64
artiq_environment_name = "artiq_5" # it can be either artiq or artiq_5 for Hosten lab systems
analog_card = "zotino" # it can be either fastino or zotino for Hosten lab systems   
research_group_name = "Hosten"
allow_skipping_images = True